import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { attachAchievementDocument, attachAchievementMedia, attachAchievementProject, attachAchievementSkill, detachAchievementDocument, detachAchievementMedia, detachAchievementProject, detachAchievementSkill, updateAchievement } from "@/app/(admin)/admin/achievements/actions";

export const dynamic = "force-dynamic";
export default async function AchievementEditor({ params }: { params: Promise<{ slug: string }> }) {
  const item = await db.achievement.findFirst({ where: { slug: (await params).slug, deletedAt: null }, include: { skills: { include: { skill: true } }, projects: { include: { project: true } }, media: { include: { media: true }, orderBy: { sortOrder: "asc" } }, documents: { include: { document: true } } } }); if (!item) notFound();
  const [skills, projects, media, documents, versions] = await Promise.all([db.skill.findMany({ where: { deletedAt: null }, include: { category: true }, orderBy: [{ category: { sortOrder: "asc" } }, { name: "asc" }] }), db.project.findMany({ where: { deletedAt: null }, orderBy: { title: "asc" } }), db.media.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" } }), db.document.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" } }), db.contentVersion.findMany({ where: { contentType: "achievement", contentId: item.id }, orderBy: { version: "desc" }, take: 12 })]);
  const skillIds = new Set(item.skills.map((entry) => entry.skillId)); const projectIds = new Set(item.projects.map((entry) => entry.projectId)); const mediaIds = new Set(item.media.map((entry) => entry.mediaId)); const documentIds = new Set(item.documents.map((entry) => entry.documentId));
  return <><p className="eyebrow">Achievement editor</p><h1>{item.title}</h1><p className="admin-intro">Recognition becomes credible when its context, contribution, and evidence remain connected.</p><form action={updateAchievement} className="editor-form project-editor"><input name="id" type="hidden" value={item.id} /><section><h2>Recognition story</h2><label>Title<input name="title" defaultValue={item.title} required /></label><label>Stable URL slug<input name="slug" defaultValue={item.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label><label>Organization<input name="organization" defaultValue={item.organization} required /></label><label>Category<select name="category" defaultValue={item.category}>{["COMPETITION", "AWARD", "SCHOLARSHIP", "RECOGNITION", "HAKI", "CERTIFICATION"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Date<input name="date" type="date" defaultValue={item.date.toISOString().slice(0, 10)} required /></label><label>Context<textarea name="context" defaultValue={item.context ?? ""} rows={5} /></label><label>My role<textarea name="myRole" defaultValue={item.myRole ?? ""} rows={4} /></label><label>Result<textarea name="result" defaultValue={item.result ?? ""} rows={3} /></label><label>Why it matters<textarea name="significance" defaultValue={item.significance ?? ""} rows={4} /></label><label>Credential<input name="credential" defaultValue={item.credential ?? ""} /></label><label>Credential URL<input name="credentialUrl" type="url" defaultValue={item.credentialUrl ?? ""} /></label></section><section><h2>Publishing</h2><label>State<select name="status" defaultValue={item.status}>{["DRAFT", "REVIEW", "READY", "PUBLISHED", "ARCHIVED", "UNLISTED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={item.visibility}>{["PUBLIC", "RESTRICTED", "PRIVATE"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Homepage feature<select name="featured" defaultValue={String(item.featured)}><option value="false">Not featured</option><option value="true">Featured</option></select></label><button className="button">Save achievement</button></section></form>
    <RelationWorkspace title="Skills" items={item.skills.map(({ skill }) => ({ id: skill.id, label: skill.name }))} action={detachAchievementSkill} achievementId={item.id} options={skills.filter((entry) => !skillIds.has(entry.id)).map((entry) => ({ id: entry.id, label: `${entry.category.name} — ${entry.name}` }))} attach={attachAchievementSkill} attachLabel="Attach capability" />
    <RelationWorkspace title="Related projects" items={item.projects.map(({ project }) => ({ id: project.id, label: project.title }))} action={detachAchievementProject} achievementId={item.id} options={projects.filter((entry) => !projectIds.has(entry.id)).map((entry) => ({ id: entry.id, label: entry.title }))} attach={attachAchievementProject} attachLabel="Attach project" />
    <RelationWorkspace title="Media evidence" items={item.media.map((entry) => ({ id: entry.id, label: entry.media.title ?? entry.media.url, value: entry.id }))} action={detachAchievementMedia} achievementId={item.id} options={media.filter((entry) => !mediaIds.has(entry.id)).map((entry) => ({ id: entry.id, label: entry.title ?? entry.url }))} attach={attachAchievementMedia} attachLabel="Attach media from library" />
    <RelationWorkspace title="Documents" items={item.documents.map(({ document }) => ({ id: document.id, label: `${document.type.toLowerCase()} — ${document.title}` }))} action={detachAchievementDocument} achievementId={item.id} options={documents.filter((entry) => !documentIds.has(entry.id)).map((entry) => ({ id: entry.id, label: `${entry.type.toLowerCase()} — ${entry.title}` }))} attach={attachAchievementDocument} attachLabel="Attach document from library" />
    <section className="admin-workspace"><h2>Version history</h2><div className="editor-history">{versions.length ? versions.map((version) => <article key={version.id}><b>v{version.version}</b><span>{version.changeNote ?? "Updated"}</span><small>{version.createdAt.toLocaleString("en-GB")}</small></article>) : <p className="admin-empty">The first save will create a version snapshot.</p>}</div></section></>;
}
function RelationWorkspace({ title, items, action, achievementId, options, attach, attachLabel }: { title: string; items: { id: string; label: string; value?: string }[]; action: (formData: FormData) => Promise<void>; achievementId: string; options: { id: string; label: string }[]; attach: (formData: FormData) => Promise<void>; attachLabel: string }) { return <section className="admin-workspace"><h2>{title}</h2><div className="editor-chips">{items.map((entry) => <form action={action} key={entry.id}><span>{entry.label}</span><input name="achievementId" type="hidden" value={achievementId} /><input name="value" type="hidden" value={entry.value ?? entry.id} /><button aria-label={`Detach ${entry.label}`}>×</button></form>)}</div>{options.length > 0 && <form action={attach} className="inline-editor"><input name="achievementId" type="hidden" value={achievementId} /><select name="value" defaultValue="" required><option disabled value="">Select an item</option>{options.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select><button className="button">{attachLabel}</button></form>}</section>; }
