"use server";
import { ContentStatus, Prisma, Visibility } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
const schema = z.object({ type: z.enum(["experience", "achievement", "skill"]), id: z.string().uuid(), status: z.nativeEnum(ContentStatus).optional(), visibility: z.nativeEnum(Visibility), featured: z.enum(["true", "false"]).optional() });
export async function updateContentState(formData: FormData) { const user = await requireAdmin(); const parsed = schema.safeParse(Object.fromEntries(formData)); if (!parsed.success) throw new Error("Invalid content update."); const { type, id, status, visibility, featured } = parsed.data; if (type === "experience") await db.experience.update({ where: { id }, data: { status, visibility, featured: featured === "true" } }); if (type === "achievement") await db.achievement.update({ where: { id }, data: { status, visibility, featured: featured === "true" } }); if (type === "skill") await db.skill.update({ where: { id }, data: { visibility, featured: featured === "true" } }); await db.auditLog.create({ data: { userId: user.id, action: "UPDATE", entityType: type, entityId: id, metadata: { status, visibility, featured } } }); revalidatePath("/"); revalidatePath("/experience"); revalidatePath("/capabilities"); revalidatePath("/archive"); redirect(`/admin/content/${type}`); }

const lifecycleSchema = z.object({ type: z.enum(["experience", "achievement", "skill"]), id: z.string().uuid() });
function refresh(type: "experience" | "achievement" | "skill") { ["/", "/experience", "/achievements", "/capabilities", "/archive", `/admin/content/${type}`].forEach((path) => revalidatePath(path)); }
export async function archiveContent(formData: FormData) { const user = await requireAdmin(); const parsed = lifecycleSchema.parse(Object.fromEntries(formData)); const { type, id } = parsed; const item = type === "experience" ? await db.experience.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, deletedAt: new Date() } }) : type === "achievement" ? await db.achievement.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, deletedAt: new Date() } }) : await db.skill.update({ where: { id }, data: { deletedAt: new Date() } }); await db.contentVersion.create({ data: { contentType: type, contentId: id, version: await db.contentVersion.count({ where: { contentType: type, contentId: id } }) + 1, snapshot: JSON.parse(JSON.stringify(item)) as Prisma.InputJsonValue, changeNote: "Archived through CMS.", createdById: user.id } }); await db.auditLog.create({ data: { userId: user.id, action: "ARCHIVE", entityType: type, entityId: id } }); refresh(type); redirect(`/admin/content/${type}`); }
export async function restoreContent(formData: FormData) { const user = await requireAdmin(); const parsed = lifecycleSchema.parse(Object.fromEntries(formData)); const { type, id } = parsed; if (type === "experience") await db.experience.update({ where: { id }, data: { status: ContentStatus.DRAFT, deletedAt: null } }); if (type === "achievement") await db.achievement.update({ where: { id }, data: { status: ContentStatus.DRAFT, deletedAt: null } }); if (type === "skill") await db.skill.update({ where: { id }, data: { deletedAt: null } }); await db.auditLog.create({ data: { userId: user.id, action: "RESTORE", entityType: type, entityId: id } }); refresh(type); redirect(`/admin/content/${type}`); }
