"use server";

import { AchievementCategory, ContentStatus, Prisma, Visibility } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";

const text = z.string().trim().max(12000).transform((value) => value || null);
const slug = z.string().trim().min(2).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const fields = z.object({ title: z.string().trim().min(2).max(220), slug, organization: z.string().trim().min(2).max(180), category: z.nativeEnum(AchievementCategory), date: z.coerce.date(), context: text, myRole: text, result: text, significance: text, credential: z.string().trim().max(160).transform((value) => value || null), credentialUrl: z.string().trim().url().max(2048).or(z.literal("")).transform((value) => value || null), status: z.nativeEnum(ContentStatus), visibility: z.nativeEnum(Visibility), featured: z.enum(["true", "false"]) });
const createSchema = fields.pick({ title: true, slug: true, organization: true, category: true, date: true }); const updateSchema = fields.extend({ id: z.string().uuid() }); const relation = z.object({ achievementId: z.string().uuid(), value: z.string().uuid() });
function snapshot(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
async function record(userId: string, achievementId: string, action: "CREATE" | "UPDATE" | "PUBLISH" | "ARCHIVE" | "RESTORE", note: string) { const current = await db.achievement.findUniqueOrThrow({ where: { id: achievementId }, include: { skills: true, projects: true, media: true, documents: true } }); const version = await db.contentVersion.count({ where: { contentType: "achievement", contentId: achievementId } }) + 1; await db.$transaction([db.contentVersion.create({ data: { contentType: "achievement", contentId: achievementId, version, snapshot: snapshot(current), changeNote: note, createdById: userId } }), db.auditLog.create({ data: { userId, action, entityType: "achievement", entityId: achievementId, metadata: { note } } })]); }
function refresh(slug: string) { ["/", "/achievements", `/achievements/${slug}`, "/archive", "/admin/achievements", `/admin/achievements/${slug}`, "/admin/content/achievement"].forEach((path) => revalidatePath(path)); }
export async function createAchievement(formData: FormData) { const user = await requireAdmin(); const parsed = createSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) throw new Error("Achievement needs a title, stable slug, organization, category, and date."); if (await db.achievement.findUnique({ where: { slug: parsed.data.slug }, select: { id: true } })) throw new Error("That achievement slug is already in use."); const item = await db.achievement.create({ data: { ...parsed.data, status: ContentStatus.DRAFT, visibility: Visibility.PRIVATE, featured: false } }); await record(user.id, item.id, "CREATE", "Created a private achievement draft."); refresh(item.slug); redirect(`/admin/achievements/${item.slug}`); }
export async function updateAchievement(formData: FormData) { const user = await requireAdmin(); const parsed = updateSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) throw new Error("Achievement data is invalid."); const { id, featured, ...data } = parsed.data; const item = await db.achievement.update({ where: { id }, data: { ...data, featured: featured === "true" } }); await record(user.id, id, data.status === ContentStatus.PUBLISHED ? "PUBLISH" : data.status === ContentStatus.ARCHIVED ? "ARCHIVE" : "UPDATE", "Updated achievement story and editorial settings through CMS."); refresh(item.slug); redirect(`/admin/achievements/${item.slug}`); }
async function attach(formData: FormData, type: "skill" | "project" | "media" | "document") { const user = await requireAdmin(); const { achievementId, value } = relation.parse(Object.fromEntries(formData)); if (type === "skill") await db.achievementSkill.upsert({ where: { achievementId_skillId: { achievementId, skillId: value } }, update: {}, create: { achievementId, skillId: value } }); if (type === "project") await db.achievementProject.upsert({ where: { achievementId_projectId: { achievementId, projectId: value } }, update: {}, create: { achievementId, projectId: value } }); if (type === "media") { const sortOrder = await db.achievementMedia.count({ where: { achievementId } }); await db.achievementMedia.create({ data: { achievementId, mediaId: value, sortOrder, isCover: sortOrder === 0 } }); } if (type === "document") await db.achievementDocument.create({ data: { achievementId, documentId: value } }); const item = await db.achievement.findUniqueOrThrow({ where: { id: achievementId } }); await record(user.id, achievementId, "UPDATE", `Attached ${type}.`); refresh(item.slug); }
async function detach(formData: FormData, type: "skill" | "project" | "media" | "document") { const user = await requireAdmin(); const { achievementId, value } = relation.parse(Object.fromEntries(formData)); if (type === "skill") await db.achievementSkill.delete({ where: { achievementId_skillId: { achievementId, skillId: value } } }); if (type === "project") await db.achievementProject.delete({ where: { achievementId_projectId: { achievementId, projectId: value } } }); if (type === "media") await db.achievementMedia.delete({ where: { id: value } }); if (type === "document") { const link = await db.achievementDocument.findFirstOrThrow({ where: { achievementId, documentId: value } }); await db.achievementDocument.delete({ where: { id: link.id } }); } const item = await db.achievement.findUniqueOrThrow({ where: { id: achievementId } }); await record(user.id, achievementId, "UPDATE", `Detached ${type}.`); refresh(item.slug); }
export async function attachAchievementSkill(data: FormData) { return attach(data, "skill"); } export async function detachAchievementSkill(data: FormData) { return detach(data, "skill"); } export async function attachAchievementProject(data: FormData) { return attach(data, "project"); } export async function detachAchievementProject(data: FormData) { return detach(data, "project"); } export async function attachAchievementMedia(data: FormData) { return attach(data, "media"); } export async function detachAchievementMedia(data: FormData) { return detach(data, "media"); } export async function attachAchievementDocument(data: FormData) { return attach(data, "document"); } export async function detachAchievementDocument(data: FormData) { return detach(data, "document"); }
export async function archiveAchievement(formData: FormData) { const user = await requireAdmin(); const id = z.string().uuid().parse(formData.get("id")); const item = await db.achievement.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, deletedAt: new Date() } }); await record(user.id, id, "ARCHIVE", "Archived through the achievement CMS."); refresh(item.slug); redirect("/admin/achievements"); }
export async function restoreAchievement(formData: FormData) { const user = await requireAdmin(); const id = z.string().uuid().parse(formData.get("id")); const item = await db.achievement.update({ where: { id }, data: { status: ContentStatus.DRAFT, deletedAt: null } }); await record(user.id, id, "RESTORE", "Restored as a private draft."); refresh(item.slug); redirect(`/admin/achievements/${item.slug}`); }
