import { saveProfile } from "@/app/(admin)/admin/profile/actions";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ProfileEditorPage() {
  const profile = await db.person.findFirst();
  const value = (key: keyof NonNullable<typeof profile>) => profile?.[key] ?? "";
  return <><p className="eyebrow">Profile</p><h1>Person behind the portfolio.</h1><p className="admin-intro">This is the single source for the public profile, contact details, portrait URL, and SEO description. Upload a portrait in Evidence first, then paste its public URL here.</p><form action={saveProfile} className="editor-form admin-workspace"><label>Name<input name="name" required defaultValue={value("name") as string} /></label><label>Tagline<input name="tagline" required defaultValue={value("tagline") as string} /></label><label>Headline<textarea name="headline" required rows={2} defaultValue={value("headline") as string} /></label><label>Bio<textarea name="bio" required rows={5} defaultValue={value("bio") as string} /></label><label>Philosophy<textarea name="philosophy" required rows={4} defaultValue={value("philosophy") as string} /></label><label>Email<input name="email" type="email" required defaultValue={value("email") as string} /></label><label>Location<input name="location" required defaultValue={value("location") as string} /></label><label>Availability<input name="availability" defaultValue={value("availability") as string} /></label><label>Portrait URL<input name="photoUrl" type="url" defaultValue={value("photoUrl") as string} /></label><label>CV URL<input name="cvUrl" type="url" defaultValue={value("cvUrl") as string} /></label><label>LinkedIn URL<input name="linkedin" type="url" defaultValue={value("linkedin") as string} /></label><label>GitHub URL<input name="github" type="url" defaultValue={value("github") as string} /></label><label>SEO title<input name="metaTitle" defaultValue={value("metaTitle") as string} /></label><label>SEO description<textarea name="metaDescription" rows={3} defaultValue={value("metaDescription") as string} /></label><label>Social image URL<input name="ogImage" type="url" defaultValue={value("ogImage") as string} /></label><button className="button">Save public profile</button></form></>;
}
