import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { attachExperienceDocument, attachExperienceMedia, attachExperienceProject, attachExperienceSkill, detachExperienceDocument, detachExperienceMedia, detachExperienceProject, detachExperienceSkill, updateExperience } from "@/app/(admin)/admin/experiences/actions";

export const dynamic = "force-dynamic";

export default async function ExperienceEditor({ params }: { params: Promise<{ slug: string }> }) {
  const experience = await db.experience.findFirst({ where: { slug: (await params).slug, deletedAt: null }, include: { skills: { include: { skill: true } }, projects: { include: { project: true } }, media: { include: { media: true }, orderBy: { sortOrder: "asc" } }, documents: { include: { document: true } } } });
  if (!experience) notFound();
  const [skills, projects, media, documents, versions] = await Promise.all([
    db.skill.findMany({ where: { deletedAt: null }, include: { category: true }, orderBy: [{ category: { sortOrder: "asc" } }, { name: "asc" }] }),
    db.project.findMany({ where: { deletedAt: null }, orderBy: { title: "asc" } }),
    db.media.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" } }),
    db.document.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" } }),
    db.contentVersion.findMany({ where: { contentType: "experience", contentId: experience.id }, orderBy: { version: "desc" }, take: 12 }),
  ]);
  const skillIds = new Set(experience.skills.map((item) => item.skillId)); const projectIds = new Set(experience.projects.map((item) => item.projectId)); const mediaIds = new Set(experience.media.map((item) => item.mediaId)); const documentIds = new Set(experience.documents.map((item) => item.documentId));
  return <>
    <p className="eyebrow">Experience editor</p><h1>{experience.company}</h1><p className="admin-intro">Show the work, people, projects, and evidence behind this experience. Public pages only read published public content.</p>
    <form action={updateExperience} className="editor-form project-editor"><input name="id" type="hidden" value={experience.id} />
      <section><h2>Experience story</h2><label>Company<input name="company" defaultValue={experience.company} required /></label><label>Role<input name="role" defaultValue={experience.role} required /></label><label>Stable URL slug<input name="slug" defaultValue={experience.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label><label>Employment type<select name="employmentType" defaultValue={experience.employmentType}>{["FULL_TIME", "PART_TIME", "INTERNSHIP", "CONTRACT", "FREELANCE", "VOLUNTEER"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Location<input name="location" defaultValue={experience.location ?? ""} /></label><label>Location type<input name="locationType" defaultValue={experience.locationType ?? ""} placeholder="Remote, hybrid, on-site" /></label><label>Start date<input name="startDate" type="date" defaultValue={experience.startDate.toISOString().slice(0, 10)} required /></label><label>End date<input name="endDate" type="date" defaultValue={experience.endDate?.toISOString().slice(0, 10) ?? ""} /></label><label>Current role<select name="isCurrent" defaultValue={String(experience.isCurrent)}><option value="false">No</option><option value="true">Yes</option></select></label><label>Summary<textarea name="summary" defaultValue={experience.summary} rows={5} required /></label><label>Responsibilities <small>one item per line</small><textarea name="responsibilities" defaultValue={experience.responsibilities.join("\n")} rows={7} /></label><label>Impact<textarea name="impact" defaultValue={experience.impact ?? ""} rows={4} /></label><label>Metrics JSON <small>optional array of label/value objects</small><textarea name="metrics" defaultValue={experience.metrics ? JSON.stringify(experience.metrics, null, 2) : ""} rows={5} /></label></section>
      <section><h2>Publishing</h2><label>State<select name="status" defaultValue={experience.status}>{["DRAFT", "REVIEW", "READY", "PUBLISHED", "ARCHIVED", "UNLISTED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={experience.visibility}>{["PUBLIC", "RESTRICTED", "PRIVATE"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Homepage feature<select name="featured" defaultValue={String(experience.featured)}><option value="false">Not featured</option><option value="true">Featured</option></select></label><button className="button">Save experience</button></section>
    </form>
    <RelationWorkspace title="Skills" items={experience.skills.map(({ skill }) => ({ id: skill.id, label: skill.name }))} action={detachExperienceSkill} experienceId={experience.id} options={skills.filter((item) => !skillIds.has(item.id)).map((item) => ({ id: item.id, label: `${item.category.name} — ${item.name}` }))} attach={attachExperienceSkill} attachLabel="Attach capability" />
    <RelationWorkspace title="Projects" items={experience.projects.map(({ project }) => ({ id: project.id, label: project.title }))} action={detachExperienceProject} experienceId={experience.id} options={projects.filter((item) => !projectIds.has(item.id)).map((item) => ({ id: item.id, label: item.title }))} attach={attachExperienceProject} attachLabel="Attach project" />
    <RelationWorkspace title="Media evidence" items={experience.media.map((item) => ({ id: item.id, label: item.media.title ?? item.media.url, value: item.id }))} action={detachExperienceMedia} experienceId={experience.id} options={media.filter((item) => !mediaIds.has(item.id)).map((item) => ({ id: item.id, label: item.title ?? item.url }))} attach={attachExperienceMedia} attachLabel="Attach media from library" />
    <RelationWorkspace title="Documents" items={experience.documents.map(({ document }) => ({ id: document.id, label: `${document.type.toLowerCase()} — ${document.title}` }))} action={detachExperienceDocument} experienceId={experience.id} options={documents.filter((item) => !documentIds.has(item.id)).map((item) => ({ id: item.id, label: `${item.type.toLowerCase()} — ${item.title}` }))} attach={attachExperienceDocument} attachLabel="Attach document from library" />
    <section className="admin-workspace"><h2>Version history</h2><div className="editor-history">{versions.length ? versions.map((version) => <article key={version.id}><b>v{version.version}</b><span>{version.changeNote ?? "Updated"}</span><small>{version.createdAt.toLocaleString("en-GB")}</small></article>) : <p className="admin-empty">The first save will create a version snapshot.</p>}</div></section>
  </>;
}

function RelationWorkspace({ title, items, action, experienceId, options, attach, attachLabel }: { title: string; items: { id: string; label: string; value?: string }[]; action: (formData: FormData) => Promise<void>; experienceId: string; options: { id: string; label: string }[]; attach: (formData: FormData) => Promise<void>; attachLabel: string }) {
  return <section className="admin-workspace"><h2>{title}</h2><div className="editor-chips">{items.map((item) => <form action={action} key={item.id}><span>{item.label}</span><input name="experienceId" type="hidden" value={experienceId} /><input name="value" type="hidden" value={item.value ?? item.id} /><button aria-label={`Detach ${item.label}`}>×</button></form>)}</div>{options.length > 0 && <form action={attach} className="inline-editor"><input name="experienceId" type="hidden" value={experienceId} /><select name="value" defaultValue="" required><option disabled value="">Select an item</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><button className="button">{attachLabel}</button></form>}</section>;
}
