"use server";
import { ContentStatus, Prisma, Visibility } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
const slug = z.string().trim().min(2).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/); const text = z.string().trim().max(12000).transform((v) => v || null); const list = z.string().trim().max(12000).transform((v) => v.split("\n").map((x) => x.trim()).filter(Boolean));
const org = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(2).max(160), slug, role: z.string().trim().min(2).max(160), startDate: z.coerce.date(), endDate: z.union([z.coerce.date(), z.literal("")]).transform((v) => v || null), isCurrent: z.enum(["true", "false"]), description: text, responsibilities: list, initiatives: list, impact: text, memberCount: z.union([z.coerce.number().int().min(0), z.literal("")]).transform((v) => v === "" ? null : v), departmentCount: z.union([z.coerce.number().int().min(0), z.literal("")]).transform((v) => v === "" ? null : v), status: z.nativeEnum(ContentStatus), visibility: z.nativeEnum(Visibility), sortOrder: z.coerce.number().int().min(0) });
const activity = z.object({ id: z.string().uuid().optional(), title: z.string().trim().min(2).max(180), slug, organizationId: z.string().uuid().or(z.literal("")).transform((v) => v || null), role: z.string().trim().max(160).transform((v) => v || null), date: z.union([z.coerce.date(), z.literal("")]).transform((v) => v || null), description: text, outcome: text, status: z.nativeEnum(ContentStatus), visibility: z.nativeEnum(Visibility), featured: z.enum(["true", "false"]), sortOrder: z.coerce.number().int().min(0) });
const snapshot = (v: unknown) => JSON.parse(JSON.stringify(v)) as Prisma.InputJsonValue; function refresh() { ["/beyond", "/archive", "/admin/beyond"].forEach((path) => revalidatePath(path)); }
async function audit(userId: string, type: string, id: string, action: "CREATE" | "UPDATE" | "ARCHIVE", entity: unknown) { const version = await db.contentVersion.count({ where: { contentType: type, contentId: id } }) + 1; await db.$transaction([db.contentVersion.create({ data: { contentType: type, contentId: id, version, snapshot: snapshot(entity), changeNote: `${action.toLowerCase()} via Beyond CMS.`, createdById: userId } }), db.auditLog.create({ data: { userId, action, entityType: type, entityId: id } })]); }
export async function saveOrganization(formData: FormData) { const user = await requireAdmin(); const p = org.safeParse(Object.fromEntries(formData)); if (!p.success) throw new Error("Organization data is invalid."); const { id, isCurrent, ...data } = p.data; const item = id ? await db.organization.update({ where: { id }, data: { ...data, isCurrent: isCurrent === "true" } }) : await db.organization.create({ data: { ...data, isCurrent: isCurrent === "true" } }); await audit(user.id, "organization", item.id, id ? "UPDATE" : "CREATE", item); refresh(); redirect("/admin/beyond"); }
export async function saveActivity(formData: FormData) { const user = await requireAdmin(); const p = activity.safeParse(Object.fromEntries(formData)); if (!p.success) throw new Error("Activity data is invalid."); const { id, featured, ...data } = p.data; const item = id ? await db.activity.update({ where: { id }, data: { ...data, featured: featured === "true" } }) : await db.activity.create({ data: { ...data, featured: featured === "true" } }); await audit(user.id, "activity", item.id, id ? "UPDATE" : "CREATE", item); refresh(); redirect("/admin/beyond"); }
export async function archiveBeyond(formData: FormData) { const user = await requireAdmin(); const { type, id } = z.object({ type: z.enum(["organization", "activity"]), id: z.string().uuid() }).parse(Object.fromEntries(formData)); const item = type === "organization" ? await db.organization.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, deletedAt: new Date() } }) : await db.activity.update({ where: { id }, data: { status: ContentStatus.ARCHIVED, deletedAt: new Date() } }); await audit(user.id, type, id, "ARCHIVE", item); refresh(); redirect("/admin/beyond"); }
