import { saveDocument, saveMedia, retireEvidence, uploadDocument, uploadMedia } from "@/app/(admin)/admin/evidence/actions";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function EvidencePage() {
  const [media, documents] = await Promise.all([db.media.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" }, take: 30 }), db.document.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: "desc" }, take: 30 })]);
  return <><p className="eyebrow">Evidence library</p><h1>Media and documents.</h1><p className="admin-intro">Upload portfolio assets to Neon Object Storage or register a stable external URL. PostgreSQL keeps only metadata, relationships, visibility, and the storage key.</p>
    <section className="admin-workspace"><h2>Upload media</h2><p className="admin-intro">Images, video, audio, PDF previews, and other safe file types up to 20 MB are stored in the public portfolio bucket. External URLs remain available below for larger files or approved embeds.</p><form action={uploadMedia} className="editor-form compact-form"><label>File<input name="file" type="file" required /></label><label>Type<select name="type" defaultValue="IMAGE"><option>IMAGE</option><option>VIDEO</option><option>PDF_PREVIEW</option><option>AUDIO</option><option>OTHER</option></select></label><label>Title<input name="title" /></label><label>Alt text<textarea name="altText" required rows={2} /></label><label>Caption<textarea name="caption" rows={2} /></label><label>Description<textarea name="description" rows={2} /></label><button className="button">Upload media</button></form></section>
    <section className="admin-workspace"><h2>Upload document</h2><p className="admin-intro">Public files use the public bucket. Restricted and private files use the private bucket and are delivered only to an authenticated admin through a temporary signed URL.</p><form action={uploadDocument} className="editor-form compact-form"><label>File<input name="file" type="file" required /></label><label>Document title<input name="title" required /></label><label>Type<select name="type" defaultValue="OTHER">{["BRD", "FRD", "SRS", "BPMN", "CERTIFICATE", "HAKI", "PRESENTATION", "REPORT", "RESUME", "OTHER"].map((type) => <option key={type}>{type}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue="PRIVATE"><option>PUBLIC</option><option>RESTRICTED</option><option>PRIVATE</option></select></label><label>Version<input name="version" /></label><label>Description<textarea name="description" rows={2} /></label><button className="button">Upload document</button></form></section>
    <section className="admin-workspace"><h2>Add media metadata</h2><form action={saveMedia} className="editor-form compact-form"><label>Asset URL<input name="url" type="url" placeholder="https://…" required /></label><label>Type<select name="type" defaultValue="IMAGE"><option>IMAGE</option><option>VIDEO</option><option>PDF_PREVIEW</option><option>AUDIO</option><option>OTHER</option></select></label><label>Title<input name="title" /></label><label>Alt text<textarea name="altText" required rows={2} /></label><label>Caption<textarea name="caption" rows={2} /></label><label>Description<textarea name="description" rows={2} /></label><button className="button">Register media</button></form></section>
    <section className="admin-workspace"><h2>Add document metadata</h2><p className="admin-intro">Do not register confidential company material as public evidence.</p><form action={saveDocument} className="editor-form compact-form"><label>Document title<input name="title" required /></label><label>File URL<input name="fileUrl" type="url" placeholder="https://…" required /></label><label>Type<select name="type" defaultValue="OTHER">{["BRD", "FRD", "SRS", "BPMN", "CERTIFICATE", "HAKI", "PRESENTATION", "REPORT", "RESUME", "OTHER"].map((type) => <option key={type}>{type}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue="PRIVATE"><option>PUBLIC</option><option>RESTRICTED</option><option>PRIVATE</option></select></label><label>Version<input name="version" /></label><label>Description<textarea name="description" rows={2} /></label><button className="button">Register document</button></form></section>
    <section className="admin-workspace"><h2>Registered media</h2><div className="editor-block-list">{media.map((item) => <form action={retireEvidence} key={item.id}><span>{item.type.toLowerCase()}</span><code>{item.title ?? item.url}</code><input name="type" type="hidden" value="media" /><input name="id" type="hidden" value={item.id} /><button className="button">Retire</button></form>)}{!media.length && <p className="admin-empty">No media metadata registered yet.</p>}</div></section>
    <section className="admin-workspace"><h2>Registered documents</h2><div className="editor-block-list">{documents.map((item) => <form action={retireEvidence} key={item.id}><span>{item.type.toLowerCase()} · {item.visibility.toLowerCase()}</span><code>{item.title}</code><input name="type" type="hidden" value="document" /><input name="id" type="hidden" value={item.id} /><button className="button">Retire</button></form>)}{!documents.length && <p className="admin-empty">No document metadata registered yet.</p>}</div></section>
  </>;
}
