import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { addProjectBlock, addProjectRole, addProjectSkill, addProjectTag, removeProjectBlock, removeProjectRole, removeProjectSkill, removeProjectTag, updateProject } from "@/app/(admin)/admin/projects/actions";

export const dynamic = "force-dynamic";
const narrativeFields = [["problem", "Problem"], ["context", "Context"], ["objective", "Objective"], ["myRole", "My role"], ["approach", "Approach"], ["process", "Process"], ["solution", "Solution"], ["implementation", "Implementation"], ["collaboration", "Collaboration"], ["result", "Result"], ["challenges", "Challenges"], ["learnings", "Learning"]] as const;

export default async function AdminProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const project = await db.project.findFirst({ where: { slug: (await params).slug, deletedAt: null }, include: { roles: { orderBy: { sortOrder: "asc" } }, skills: { include: { skill: true } }, tags: { include: { tag: true } }, contentBlocks: { orderBy: { sortOrder: "asc" } } } });
  if (!project) notFound();
  const [skills, tags, versions] = await Promise.all([db.skill.findMany({ where: { deletedAt: null }, orderBy: [{ category: { sortOrder: "asc" } }, { name: "asc" }], include: { category: true } }), db.tag.findMany({ orderBy: { name: "asc" } }), db.contentVersion.findMany({ where: { contentType: "project", contentId: project.id }, orderBy: { version: "desc" }, take: 8 })]);
  const attachedSkillIds = new Set(project.skills.map(({ skillId }) => skillId)); const attachedTagIds = new Set(project.tags.map(({ tagId }) => tagId));
  return <>
    <p className="eyebrow">Project editor</p><h1>{project.title}</h1><p className="admin-intro">Edit the story once; public pages and recruiter views use the same evidence.</p>
    <form action={updateProject} className="editor-form project-editor"><input name="id" type="hidden" value={project.id} />
      <section><h2>Story</h2><label>Title<input name="title" defaultValue={project.title} required /></label><label>Subtitle<input name="subtitle" defaultValue={project.subtitle ?? ""} /></label><label>Project type<select name="projectType" defaultValue={project.projectType}>{["PROFESSIONAL", "ACADEMIC", "COMPETITION", "PERSONAL", "ORGANIZATIONAL", "EXPERIMENT"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Overview<textarea name="overview" defaultValue={project.overview} required rows={5} /></label>{narrativeFields.map(([name, label]) => <label key={name}>{label}<textarea name={name} defaultValue={project[name] ?? ""} rows={4} /></label>)}</section>
      <section><h2>Publishing</h2><label>Publishing state<select name="status" defaultValue={project.status}>{["DRAFT", "REVIEW", "READY", "PUBLISHED", "ARCHIVED", "UNLISTED"].map((status) => <option key={status}>{status}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={project.visibility}>{["PUBLIC", "RESTRICTED", "PRIVATE"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Homepage feature<select name="featured" defaultValue={String(project.featured)}><option value="false">Not featured</option><option value="true">Featured</option></select></label><label>Search indexing<select name="noIndex" defaultValue={String(project.noIndex)}><option value="false">Allow indexing</option><option value="true">No index</option></select></label></section>
      <section><h2>Links & SEO</h2><label>GitHub URL<input type="url" name="githubUrl" defaultValue={project.githubUrl ?? ""} /></label><label>Demo URL<input type="url" name="demoUrl" defaultValue={project.demoUrl ?? ""} /></label><label>Meta title<input name="metaTitle" defaultValue={project.metaTitle ?? ""} /></label><label>Meta description<textarea name="metaDescription" defaultValue={project.metaDescription ?? ""} rows={3} /></label><label>Canonical URL<input type="url" name="canonicalUrl" defaultValue={project.canonicalUrl ?? ""} /></label><label>Open Graph title<input name="ogTitle" defaultValue={project.ogTitle ?? ""} /></label><label>Open Graph description<textarea name="ogDescription" defaultValue={project.ogDescription ?? ""} rows={3} /></label><label>Open Graph image URL<input type="url" name="ogImage" defaultValue={project.ogImage ?? ""} /></label></section>
      <button className="button" type="submit">Save project story</button>
    </form>
    <section className="admin-workspace"><h2>Roles</h2><div className="editor-chips">{project.roles.map((role) => <form action={removeProjectRole} key={role.id}><span>{role.title}{role.description ? ` — ${role.description}` : ""}</span><input name="id" type="hidden" value={role.id} /><button aria-label={`Remove ${role.title}`}>×</button></form>)}</div><form action={addProjectRole} className="inline-editor"><input name="projectId" type="hidden" value={project.id} /><input name="title" placeholder="Role title" required /><input name="description" placeholder="Optional evidence/context" /><button className="button">Add role</button></form></section>
    <section className="admin-workspace"><h2>Skills</h2><div className="editor-chips">{project.skills.map(({ skill }) => <form action={removeProjectSkill} key={skill.id}><span>{skill.name}</span><input name="projectId" type="hidden" value={project.id} /><input name="value" type="hidden" value={skill.id} /><button aria-label={`Remove ${skill.name}`}>×</button></form>)}</div><form action={addProjectSkill} className="inline-editor"><input name="projectId" type="hidden" value={project.id} /><select name="value" defaultValue="" required><option value="" disabled>Select a capability</option>{skills.filter((skill) => !attachedSkillIds.has(skill.id)).map((skill) => <option key={skill.id} value={skill.id}>{skill.category.name} — {skill.name}</option>)}</select><button className="button">Attach skill</button></form></section>
    <section className="admin-workspace"><h2>Tags</h2><div className="editor-chips">{project.tags.map(({ tag }) => <form action={removeProjectTag} key={tag.id}><span>{tag.name}</span><input name="projectId" type="hidden" value={project.id} /><input name="value" type="hidden" value={tag.id} /><button aria-label={`Remove ${tag.name}`}>×</button></form>)}</div>{tags.length ? <form action={addProjectTag} className="inline-editor"><input name="projectId" type="hidden" value={project.id} /><select name="value" defaultValue="" required><option value="" disabled>Select a tag</option>{tags.filter((tag) => !attachedTagIds.has(tag.id)).map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select><button className="button">Attach tag</button></form> : <p className="admin-empty">Create tags through the upcoming shared content workspace.</p>}</section>
    <section className="admin-workspace"><h2>Structured story blocks</h2><p className="admin-intro">Use blocks for supporting editorial material that does not belong in the core case-study fields.</p><div className="editor-block-list">{project.contentBlocks.map((block) => <form action={removeProjectBlock} key={block.id}><span>{block.type.toLowerCase()}</span><code>{JSON.stringify(block.data)}</code><input name="id" type="hidden" value={block.id} /><button className="button">Remove</button></form>)}</div><form action={addProjectBlock} className="editor-form compact-form"><input name="projectId" type="hidden" value={project.id} /><label>Block type<select name="type" defaultValue="TEXT"><option>HEADING</option><option>TEXT</option><option>QUOTE</option><option>LIST</option></select></label><label>Content<textarea name="content" rows={4} placeholder="For LIST, use one item per line." required /></label><button className="button">Add story block</button></form></section>
    <section className="admin-workspace"><h2>Recent editorial history</h2><div className="editor-history">{versions.length ? versions.map((version) => <article key={version.id}><b>v{version.version}</b><span>{version.changeNote ?? "Updated"}</span><small>{version.createdAt.toLocaleString("en-GB")}</small></article>) : <p className="admin-empty">The first save will create a version snapshot.</p>}</div></section>
  </>;
}
